export const requestBody = {
    business: 'xxx',
    startTime: '2019-01-01',
    endTime: '2019-01-01',
    groupBys: ['daily'],
    measures: ['gp', 'sales', 'Customer.newVsReturn', 'averageSale', 'ALL'],
    filters: [{ name: 'storeid', value: 'xxx', expression: '=' }],
    sorts: [
        { name: 'date', order: 'desc' },
        { name: 'createdtime', order: 'asc' },
    ],
    size: 10,
    page: 1,
};

export const dataRows = [
    {
        serviceChange: 0,
        tax: 10,
        rounding: 0,
        cost: 0,
        sales: 10,
        returns: 2,
        count: 20,
    },
    {
        serviceChange: 0,
        tax: 10,
        rounding: 0,
        cost: 0,
        sales: 10,
        returns: 2,
        count: 20,
    },
    {
        serviceChange: 0,
        tax: 10,
        rounding: 0,
        cost: 0,
        sales: 10,
        returns: 2,
        count: 20,
    },
    {
        serviceChange: 0,
        tax: 10,
        rounding: 0,
        cost: 0,
        sales: 10,
        returns: 2,
        count: 1,
    },
];

export const jsonData = {
    average: 0.66,
    count: 61,
    data: [
        {
            averageSale: -0.1,
            cost: 0,
            count: 20,
            gp: 0,
            netSales: -2,
            returns: 2,
            rounding: 0,
            sales: 10,
            serviceChange: 0,
            tax: 10,
            tendered: 8,
        },
        {
            averageSale: -0.1,
            cost: 0,
            count: 20,
            gp: 0,
            netSales: -2,
            returns: 2,
            rounding: 0,
            sales: 10,
            serviceChange: 0,
            tax: 10,
            tendered: 8,
        },
        {
            averageSale: -0.1,
            cost: 0,
            count: 20,
            gp: 0,
            netSales: -2,
            returns: 2,
            rounding: 0,
            sales: 10,
            serviceChange: 0,
            tax: 10,
            tendered: 8,
        },
        {
            averageSale: -2,
            cost: 0,
            count: 1,
            gp: 0,
            netSales: -2,
            returns: 2,
            rounding: 0,
            sales: 10,
            serviceChange: 0,
            tax: 10,
            tendered: 8,
        },
    ],
    netSalesAvg: -0.13,
    netSalesTotal: -8,
    newUserCount: 1,
    newUserSales: -2,
    returnUserCount: 3,
    returnUserSales: -6,
    total: 40,
};
