	 ('storehub_mongo','transactionrecords__staging__2022-03-16t20:30','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2022-03-16t20:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2022-03-17t02:20','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecords__staging__2022-03-17t02:20','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2022-03-18t01:30','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2022-03-18t01:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2023-11-01t16:30','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2023-11-01t16:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2023-11-23t11:14','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2023-11-23t11:14','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t13:32','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t13:32','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t13:47','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t13:47','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t15:44','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t15:44','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t18:48','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t18:48','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t18:53','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__2024-09-03t18:53','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__staging__copy','_id','character varying'),
	 ('storehub_mongo','transactionrecords__staging__copy','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__suborders','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecords__suborders','comments','character varying'),
	 ('storehub_mongo','transactionrecords__suborders','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__suborders','isprinted','boolean'),
	 ('storehub_mongo','transactionrecords__suborders','printedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__suborders','submitid','character varying'),
	 ('storehub_mongo','transactionrecords__suborders','submittedby','character varying'),
	 ('storehub_mongo','transactionrecords__suborders','submittedbyphone','character varying'),
	 ('storehub_mongo','transactionrecords__suborders','submittedfrom','character varying'),
	 ('storehub_mongo','transactionrecords__suborders','submittedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecords__suborders','transactionrecords_foreignkey','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','addonbircompliance.athleteandcoachdiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','addonbircompliance.collectedinfo','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','addonbircompliance.discounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','addonbircompliance.medalofvalordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','addonbircompliance.soloparentdiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','amusementtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','appversion','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','business','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','cancelledat','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','cancelledby','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','cancelledsource','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','cashtendered','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','channel','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','comment','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','cost','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','createdtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','customerid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','depositamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','discount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','einvoiceinfo.documentid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','einvoiceinfo.documenttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','einvoiceinfo.einvoicestatus','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','einvoiceinfo.statusupdatedat','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','emailreceipt','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','employeenumber','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','enablecashback','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','failedtosendmembershipstatsqueue','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','failedtoupdateinventory','boolean');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','failedtoupdateloyalty','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','fixedfee','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','headcount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','inventorychangemsgtrackinfo.eventid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','inventorychangemsgtrackinfo.issendmsg','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','inventorychangemsgtrackinfo.sendmsgstartat','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','invoiceseqnumber','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','iscancelled','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','lastuploadedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','minno','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','modifiedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','originalreceiptnumber','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','otherreason','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','paymentmethod','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pendingtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pickupdate','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pickupid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','preorderby','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','preorderdate','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','preorderid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pwdcount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','pwddiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','receiptnumber','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','receiptnumbersbeforefix','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','registerid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','registernumber','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','returnreason','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','returnstatus','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','roundedamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','saleschannel','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','seniordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','seniorscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','seqnumbercreatedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','sequencenumber','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','servedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','servicecharge','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','servicechargerate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','servicechargetax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','storeid','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','subtotal','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','tableid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','takeawaycharges','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','taxablesales','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','taxexemptedsales','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','total','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','totaldeductedtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','transactionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','transactiontype','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids','voidnumber','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','voidseqnumber','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids','zeroratedsales','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','cost','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','coveredbysh','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','purchasechannel','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','value','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','vouchercode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__appliedvoucher','voucherid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation','fullprice','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','deductedtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','discount','numeric');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','promotionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','subtype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','transactionrecordwithduplicatedids__calculation_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__discounts','type','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','subtotal','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','total','numeric');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','transactionrecordwithduplicatedids__calculation_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__original','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','isamusementtax','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','isvatexempted','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','transactionrecordwithduplicatedids__calculation_foreignkey','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__calculation__taxes','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','adhocdiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','athleteandcoachdiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','comments','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','cost','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','discount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','discounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','discountvalue','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','fullbilldiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','image','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','isamusementtax','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','ishalal','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','isservicechargenotapplicable','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','istakeaway','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','isvatexempted','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','itemchannel','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','itemtype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','lockeddate','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','lockedquantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','loyaltydiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','medalofvalordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','notes','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','orderingvalue','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','originalitemid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','productid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','promotiondiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','pwddiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','quantity','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','refundedquantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','seniordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','sn','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','soloparentdiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','source','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','sourcevalue','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','status','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','submitid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','subtotal','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','takeawaycharge','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','taxableamount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','taxexemptamount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','title','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','total','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','totaldeductedtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','unitprice','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items','zeroratedsales','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation','fullprice','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','deductedtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','discount','numeric');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','promotionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','subtype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','transactionrecordwithduplicatedids__items__calculation_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__discounts','type','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','subtotal','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','total','numeric');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','transactionrecordwithduplicatedids__items__calculation_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__original','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','isamusementtax','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','isvatexempted','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','transactionrecordwithduplicatedids__items__calculation_foreignkey','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__calculation__taxes','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','lockeddate','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','lockedquantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','productid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','quantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__componentsusages','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','discount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','subtotal','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','total','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__display','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','transactionrecordwithduplicatedids__items_foreignkey','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','type','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__manualdiscount','value','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','category','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','displayprice','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','image','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','inventorytype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','isamusementtax','boolean');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','ishalal','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','isvatexempted','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','originaldisplayprice','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','originimage','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','productid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','productparentid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','tags','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','title','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','trackinventory','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__productinfo','unitprice','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','discount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','discounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','originaldiscounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','promotioncode','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','promotionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','promotionname','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','promotiontype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','pwddiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','quantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','seniordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','shippingfeediscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','storehubpaidpercentage','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','taxableamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','taxexemptamount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','uniquepromotioncode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__promotions','uniquepromotioncodeid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','optionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','optionvalue','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','quantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','transactionrecordwithduplicatedids__items_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__selectedoptions','variationid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','rate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','transactionrecordwithduplicatedids__items_foreignkey','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__items__servicechargeinfo','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__location','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__location','coordinates','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__location','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__location','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__location','type','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','discountedtax','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','displaydiscount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','loyaltytype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','spentvalue','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','taxrate','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__loyaltydiscounts','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','amount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','cardname','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','cardno','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','cashtendered','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','changeamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','isdeposit','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','isonline','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','mpostxnid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','paymentgateway','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','paymentmethod','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','paymentmethodid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','paymentprovider','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','paymentprovidermid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','roundedamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','subtype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','approvedate','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','approver','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','approvereason','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','transactionrecordwithduplicatedids__payments_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__payments__manualapproveinfo','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','discount','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','discounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','originaldiscounttype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','promotioncode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','promotionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','promotionname','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','promotiontype','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','pwddiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','quantity','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','seniordiscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','shippingfeediscount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','storehubpaidpercentage','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','tax','numeric'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','taxableamount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','taxcode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','taxexemptamount','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','uniquepromotioncode','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__promotions','uniquepromotioncodeid','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','actionrequired','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','comment','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','completedtime','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','failedtoupdateinventory','boolean'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','inventoryaction','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','productid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','skunumber','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','sn','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','title','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','_id','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','optionid','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','optionvalue','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','quantity','double precision'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','transactionrecordwithduplicatedids__returnprocess_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','transactionrecordwithduplicatedids_foreignkey','character varying'),
	 ('storehub_mongo','transactionrecordwithduplicatedids__returnprocess__selectedoptions','variationid','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','transactionstatistics','_id','character varying'),
	 ('storehub_mongo','transactionstatistics','businessname','character varying'),
	 ('storehub_mongo','transactionstatistics','createtime','timestamp without time zone'),
	 ('storehub_mongo','transactionstatistics','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','transactionstatistics','iscancelled','boolean'),
	 ('storehub_mongo','transactionstatistics','receiptnumber','character varying'),
	 ('storehub_mongo','transactionstatistics','updatetime','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs','_id','character varying'),
	 ('storehub_mongo','useractionlogs','action','character varying'),
	 ('storehub_mongo','useractionlogs','additionalinfo','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','useractionlogs','business','character varying'),
	 ('storehub_mongo','useractionlogs','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs','ipaddress','character varying'),
	 ('storehub_mongo','useractionlogs','notes','character varying'),
	 ('storehub_mongo','useractionlogs','registerid','double precision'),
	 ('storehub_mongo','useractionlogs','source','character varying'),
	 ('storehub_mongo','useractionlogs','storeid','character varying'),
	 ('storehub_mongo','useractionlogs','time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs','user','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-16t20:30','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','useractionlogs__staging__2022-03-16t20:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-17t02:20','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-17t02:20','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-18t01:30','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-18t01:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-18t02:20','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2022-03-18t02:20','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2023-11-01t16:30','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2023-11-01t16:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2023-11-23t11:14','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','useractionlogs__staging__2023-11-23t11:14','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t13:32','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t13:32','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t13:47','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t13:47','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t15:44','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t15:44','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t18:48','_id','character varying'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t18:48','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t18:53','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','useractionlogs__staging__2024-09-03t18:53','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','userjobs','_id','character varying'),
	 ('storehub_mongo','userjobs','business','character varying'),
	 ('storehub_mongo','userjobs','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','userjobs','employeeid','character varying'),
	 ('storehub_mongo','userjobs','error','character varying'),
	 ('storehub_mongo','userjobs','jobtype','character varying'),
	 ('storehub_mongo','userjobs','progress','double precision'),
	 ('storehub_mongo','userjobs','resultsfile','character varying'),
	 ('storehub_mongo','userjobs','status','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','userjobs','time','timestamp without time zone'),
	 ('storehub_mongo','userjobs','uploadedfile','character varying'),
	 ('storehub_mongo','userjobs__staging__2022-03-16t20:30','_id','character varying'),
	 ('storehub_mongo','userjobs__staging__2022-03-16t20:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','userjobs__staging__2022-03-17t02:20','_id','character varying'),
	 ('storehub_mongo','userjobs__staging__2022-03-17t02:20','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','userjobs__staging__2022-03-18t01:30','_id','character varying'),
	 ('storehub_mongo','userjobs__staging__2022-03-18t01:30','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','vouchers','_id','character varying'),
	 ('storehub_mongo','vouchers','applicablebusiness','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','vouchers','appliedsources','character varying'),
	 ('storehub_mongo','vouchers','business','character varying'),
	 ('storehub_mongo','vouchers','category','character varying'),
	 ('storehub_mongo','vouchers','channel','double precision'),
	 ('storehub_mongo','vouchers','consumerid','character varying'),
	 ('storehub_mongo','vouchers','cost','numeric'),
	 ('storehub_mongo','vouchers','coveredbysh','boolean'),
	 ('storehub_mongo','vouchers','createdbyorderid','character varying'),
	 ('storehub_mongo','vouchers','createdtime','timestamp without time zone'),
	 ('storehub_mongo','vouchers','currency','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','vouchers','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','vouchers','minspend','double precision'),
	 ('storehub_mongo','vouchers','modifiedtime','timestamp without time zone'),
	 ('storehub_mongo','vouchers','name','character varying'),
	 ('storehub_mongo','vouchers','purchasechannel','character varying'),
	 ('storehub_mongo','vouchers','redeemedorderid','character varying'),
	 ('storehub_mongo','vouchers','remarks','character varying'),
	 ('storehub_mongo','vouchers','status','character varying'),
	 ('storehub_mongo','vouchers','validfrom','timestamp without time zone'),
	 ('storehub_mongo','vouchers','validto','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','vouchers','value','double precision'),
	 ('storehub_mongo','vouchers','vouchercode','character varying'),
	 ('storehub_mongo','xeroproductsmappings','_id','character varying'),
	 ('storehub_mongo','xeroproductsmappings','businessname','character varying'),
	 ('storehub_mongo','xeroproductsmappings','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xeroproductsmappings','productsmapping','character varying'),
	 ('storehub_mongo','xerosettings','_id','character varying'),
	 ('storehub_mongo','xerosettings','accesstoken','character varying'),
	 ('storehub_mongo','xerosettings','accesstokenexpiresin','double precision'),
	 ('storehub_mongo','xerosettings','accesstokensecret','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings','accountmapping','character varying'),
	 ('storehub_mongo','xerosettings','businessname','character varying'),
	 ('storehub_mongo','xerosettings','companyid','character varying'),
	 ('storehub_mongo','xerosettings','customerid','character varying'),
	 ('storehub_mongo','xerosettings','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings','expiresat','double precision'),
	 ('storehub_mongo','xerosettings','firstconnected','boolean'),
	 ('storehub_mongo','xerosettings','hasrequestedstart','boolean'),
	 ('storehub_mongo','xerosettings','isallproductsmatched','boolean'),
	 ('storehub_mongo','xerosettings','oauthexpiresat','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings','oauthsessionhandle','character varying'),
	 ('storehub_mongo','xerosettings','organizationname','character varying'),
	 ('storehub_mongo','xerosettings','pausereason','character varying'),
	 ('storehub_mongo','xerosettings','paymentmethodmapping','character varying'),
	 ('storehub_mongo','xerosettings','previousstatus','character varying'),
	 ('storehub_mongo','xerosettings','refreshtoken','character varying'),
	 ('storehub_mongo','xerosettings','refreshtokenexpiresin','double precision'),
	 ('storehub_mongo','xerosettings','refundfromaccountid','character varying'),
	 ('storehub_mongo','xerosettings','requesttoken','character varying'),
	 ('storehub_mongo','xerosettings','requesttokensecret','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings','starttime','timestamp without time zone'),
	 ('storehub_mongo','xerosettings','state','character varying'),
	 ('storehub_mongo','xerosettings','status','character varying'),
	 ('storehub_mongo','xerosettings','taxcodemapping','character varying'),
	 ('storehub_mongo','xerosettings','unmappedtaxcode','character varying'),
	 ('storehub_mongo','xerosettings__accounts','_id','character varying'),
	 ('storehub_mongo','xerosettings__accounts','code','character varying'),
	 ('storehub_mongo','xerosettings__accounts','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings__accounts','enablepaymentstoaccount','boolean'),
	 ('storehub_mongo','xerosettings__accounts','id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings__accounts','name','character varying'),
	 ('storehub_mongo','xerosettings__accounts','type','character varying'),
	 ('storehub_mongo','xerosettings__accounts','xerosettings_foreignkey','character varying'),
	 ('storehub_mongo','xerosettings__qboaccounts','_id','character varying'),
	 ('storehub_mongo','xerosettings__qboaccounts','classification','character varying'),
	 ('storehub_mongo','xerosettings__qboaccounts','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings__qboaccounts','id','character varying'),
	 ('storehub_mongo','xerosettings__qboaccounts','name','character varying'),
	 ('storehub_mongo','xerosettings__qboaccounts','xerosettings_foreignkey','character varying'),
	 ('storehub_mongo','xerosettings__qbopaymentmethods','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings__qbopaymentmethods','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings__qbopaymentmethods','paymentmethodid','character varying'),
	 ('storehub_mongo','xerosettings__qbopaymentmethods','paymentmethodname','character varying'),
	 ('storehub_mongo','xerosettings__qbopaymentmethods','xerosettings_foreignkey','character varying'),
	 ('storehub_mongo','xerosettings__qbotaxcodes','_id','character varying'),
	 ('storehub_mongo','xerosettings__qbotaxcodes','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings__qbotaxcodes','taxcodeid','character varying'),
	 ('storehub_mongo','xerosettings__qbotaxcodes','taxcodename','character varying'),
	 ('storehub_mongo','xerosettings__qbotaxcodes','xerosettings_foreignkey','character varying'),
	 ('storehub_mongo','xerosettings__taxcodes','_id','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','xerosettings__taxcodes','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','xerosettings__taxcodes','taxcodeid','character varying'),
	 ('storehub_mongo','xerosettings__taxcodes','taxcodename','character varying'),
	 ('storehub_mongo','xerosettings__taxcodes','xerosettings_foreignkey','character varying'),
	 ('storehub_mongo','zreadings','_id','character varying'),
	 ('storehub_mongo','zreadings','amusementtax','double precision'),
	 ('storehub_mongo','zreadings','athleteandcoachdiscount','double precision'),
	 ('storehub_mongo','zreadings','business','character varying'),
	 ('storehub_mongo','zreadings','closetime','timestamp without time zone'),
	 ('storehub_mongo','zreadings','data_modified_time','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','endornumber','character varying'),
	 ('storehub_mongo','zreadings','endtrxnumber','character varying'),
	 ('storehub_mongo','zreadings','extendedinfoformall.customercount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.discountedtrxcount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.newvoidamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.newvoidnumber','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.oldvoidamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.oldvoidnumber','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatablenewnet','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatableoldnet','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','extendedinfoformall.vatablerefundamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatablevoidamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatexemptnewnet','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatexemptoldnet','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatexemptrefundamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.vatexemptvoidamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.voidamount','double precision'),
	 ('storehub_mongo','zreadings','extendedinfoformall.voidtrxcount','double precision'),
	 ('storehub_mongo','zreadings','grosssales','double precision'),
	 ('storehub_mongo','zreadings','headcount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','medalofvalordiscount','double precision'),
	 ('storehub_mongo','zreadings','minno','character varying'),
	 ('storehub_mongo','zreadings','netsales','double precision'),
	 ('storehub_mongo','zreadings','newgross','double precision'),
	 ('storehub_mongo','zreadings','newnet','double precision'),
	 ('storehub_mongo','zreadings','oldgross','double precision'),
	 ('storehub_mongo','zreadings','oldnet','double precision'),
	 ('storehub_mongo','zreadings','ptu','character varying'),
	 ('storehub_mongo','zreadings','pwddiscount','double precision'),
	 ('storehub_mongo','zreadings','refundamount','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','refundtrxcount','double precision'),
	 ('storehub_mongo','zreadings','registerid','character varying'),
	 ('storehub_mongo','zreadings','regulardiscount','double precision'),
	 ('storehub_mongo','zreadings','salestrxcount','double precision'),
	 ('storehub_mongo','zreadings','scdiscount','double precision'),
	 ('storehub_mongo','zreadings','serialno','character varying'),
	 ('storehub_mongo','zreadings','servicecharge','numeric'),
	 ('storehub_mongo','zreadings','servicechargetax','double precision'),
	 ('storehub_mongo','zreadings','soloparentdiscount','double precision'),
	 ('storehub_mongo','zreadings','startornumber','character varying');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','starttrxnumber','character varying'),
	 ('storehub_mongo','zreadings','storeid','character varying'),
	 ('storehub_mongo','zreadings','tin','character varying'),
	 ('storehub_mongo','zreadings','totaldeductedvat','double precision'),
	 ('storehub_mongo','zreadings','transactionswithathleteandcoachdiscount','double precision'),
	 ('storehub_mongo','zreadings','transactionswithmedalofvalordiscount','double precision'),
	 ('storehub_mongo','zreadings','transactionswithpwddiscount','double precision'),
	 ('storehub_mongo','zreadings','transactionswithregulardiscount','double precision'),
	 ('storehub_mongo','zreadings','transactionswithscdiscount','double precision'),
	 ('storehub_mongo','zreadings','vatablesales','double precision');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings','vatamount','double precision'),
	 ('storehub_mongo','zreadings','vatexemptsales','double precision'),
	 ('storehub_mongo','zreadings','zcount','double precision'),
	 ('storehub_mongo','zreadings','zendtime','timestamp without time zone'),
	 ('storehub_mongo','zreadings','zeroratedsales','double precision'),
	 ('storehub_mongo','zreadings','zstarttime','timestamp without time zone'),
	 ('storehub_mongo','zreadings__paymentcollections','_id','character varying'),
	 ('storehub_mongo','zreadings__paymentcollections','amount','numeric'),
	 ('storehub_mongo','zreadings__paymentcollections','count','double precision'),
	 ('storehub_mongo','zreadings__paymentcollections','data_modified_time','timestamp without time zone');
INSERT INTO svv_columns (table_schema,table_name,column_name,data_type) VALUES
	 ('storehub_mongo','zreadings__paymentcollections','name','character varying'),
	 ('storehub_mongo','zreadings__paymentcollections','zreadings_foreignkey','character varying'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t13:47','_id','character varying'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t13:47','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t15:44','_id','character varying'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t15:44','data_modified_time','timestamp without time zone'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t18:53','_id','character varying'),
	 ('storehub_mongo','zreadings__staging__2024-09-03t18:53','data_modified_time','timestamp without time zone');